# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit & Integration Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  release:
    types: [published]

env:
  SURREAL_BIND: "localhost:8000"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & environment using uv
        uses: astral-sh/setup-uv@v5.3.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: ruff-action
        uses: astral-sh/ruff-action@v3.2.2

      - name: Start SurrealDB for Integration Tests
        uses: surrealdb/setup-surreal@v2.0.1

      - name: Run doctests, unit and integration tests with python ${{ matrix.python-version }}
        run: uv run --frozen pytest --doctest-modules

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/surrealdb-rpc
    steps:
      - uses: pypa/gh-action-pypi-publish@v1.12.4
